### ISSUE TITLE
No deps folder

### ISSUE THREAD

**Issue by doucga** [bluepixel00/HomeAssistant_Denon_RS232#1]
I'm running Home Assistant in a Docker container on a server. I don't have a /deps/lib/python3.8/site-packages folder. The deps folder is empty.

I tried putting __init__.py in the denon232 folder along with media_player.py. The configuration checker was OK but no media player showed up on restart.

Garry

**Comment by doucga** [comment]
I tried creating the /deps/lib/python3.8/site-packages/denon232_receiver folder and moving the __init__.py file there.

Configuration check gave me this error.

Platform error media_player.denon232 - Integration 'denon232' not found.

Garry

**Comment by doucga** [comment]
Found this in the log.

2020-09-27 16:40:33 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up denon232 platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/denon232/media_player.py", line 47, in setup_platform
    from denon232_receiver import Denon232Receiver
ImportError: cannot import name 'Denon232Receiver' from 'denon232_receiver' (unknown location)

**Comment by doucga** [comment]
Got it working and learned a little about Python at the same time.

I took everything inside __init__.py and moved it into a new file called denon232_receiver.py and left __init__.py with nothing in it.

I changed line 48 in media_player.py from 'from denon232_receiver import Denon232Receiver' to 'from .denon232_receiver import Denon232Receiver'. (added a dot in front of denon232_receiver)

Now my custom_components denon232 folder has __init__.py, denon232_receiver.py and media_player.py in it.

Commented out 
#media_player:
# - platform: denon232
#   serial_port: /dev/ttyUSB0
#   name: Receiver
in configuration.yaml

Restarted Home Assistant to reinstall the changed custom component.

Uncommented configuration.yaml again and restarted Home Assistant and voila I have media_player.receiver in Home Assistant.

Thanks for the code and hope this helps.

Garry

**Comment by bluepixel00** [comment]
huh.. It is working how I have it setup in the readme. I did this a couple years ago and just hacked it together from another integration but I never went through it to ensure it was the right way since it was working. :)  Your way seems better as you don't have to keep moving the init file in the python folder when the min python gets updated.  Do you have anything in the python folder or is everything just in the custom component folder?  Are you able to communicate with the receiver without an issue?

**Comment by bluepixel00** [comment]
Still curious why it works for me in the original config but not for you.  You mention init.py but was this actually ``__init__.py``?

**Comment by bluepixel00** [comment]
@doucga Made your change on my side and working.  I think this is the better way since it is not reliant on updating the python folder version.  Not sure if it is "normal" to keep ``__init__.py`` empty but slowly making it better.  Will update readme and files.  Thanks for your input!

**Comment by bluepixel00** [comment]
Closing out as I moved the install format  that @doucga recommended.

**Comment by doucga** [comment]
@bluepixel00 I read somewhere that the newer versions of Python don't need the __init__.py file so best practice is to leave an empty one apparently. But I know virtually nothing about Python so all my monkeying around ended up getting it to work for me. All is working well so far and I really appreciate your work on this. Thank you!

**Comment by bluepixel00** [comment]
@doucga I switched my config over to what you have and it still worked so thank you for your input!  I am glad that this is helping somebody else after spending the time working on this.  It has been pretty stable and only issues I have had over the years are changes to HA that break the component.  If I have to make any changes I will be sure to include any updates here.  Take care!
